-- =============================================================================
-- TruckGuard · Seed de alertas para testes do Route Risk Engine v2
-- =============================================================================
-- Corredor principal de teste (app): Porto → Madrid
-- Cidades cobertas: PT (6) · ES (6) · FR (3)
-- Tipos: fuel · cargo_theft · sos · full_attack
-- Janela temporal: últimos 30 dias
--
-- Execução (Supabase SQL Editor ou psql):
--   \i supabase/scripts/seed_route_risk_test.sql
-- =============================================================================

begin;

-- Colunas usadas pela app (idempotente se já existirem)
alter table public.alerts
  add column if not exists description text;

alter table public.alerts
  add column if not exists severity text;

alter table public.alerts
  add column if not exists expires_at timestamptz;

alter table public.alerts
  add column if not exists total_confirmations integer not null default 0;

alter table public.alerts
  add column if not exists total_rejections integer not null default 0;

-- Remover seed anterior (re-execução segura)
delete from public.alerts
where title like '[SEED_ROUTE_RISK]%';

insert into public.alerts (
  title,
  type,
  severity,
  latitude,
  longitude,
  time,
  confirmations,
  total_confirmations,
  total_rejections,
  resolved,
  description,
  location_text,
  city,
  region,
  country,
  created_at,
  expires_at
)
values
  -- ---------------------------------------------------------------------------
  -- PORTUGAL
  -- ---------------------------------------------------------------------------
  (
    '[SEED_ROUTE_RISK] Furto combustível — Lisboa',
    'fuel',
    'urgent',
    38.7412,
    -9.1521,
    '06:40',
    4,
    4,
    0,
    false,
    'Posto na A2, saída Lisboa',
    'A2, Lisboa',
    'Lisboa',
    'Lisboa',
    'Portugal',
    now() - interval '2 days 3 hours',
    now() + interval '18 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Lisboa',
    'cargo_theft',
    'watch',
    38.7156,
    -9.1284,
    '14:15',
    2,
    2,
    1,
    false,
    'Parque industrial Alcântara',
    'Alcântara, Lisboa',
    'Lisboa',
    'Lisboa',
    'Portugal',
    now() - interval '8 days 5 hours',
    now() + interval '12 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Lisboa',
    'sos',
    'critical',
    38.7289,
    -9.1712,
    '22:08',
    6,
    6,
    0,
    false,
    'Motorista pede apoio na CREL',
    'CREL, Lisboa',
    'Lisboa',
    'Lisboa',
    'Portugal',
    now() - interval '1 day 11 hours',
    now() + interval '6 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Lisboa',
    'full_attack',
    'critical',
    38.7063,
    -9.0956,
    '03:22',
    5,
    5,
    0,
    false,
    'Tentativa de assalto em área de descanso',
    'Área de serviço, Lisboa',
    'Lisboa',
    'Lisboa',
    'Portugal',
    now() - interval '5 days 2 hours',
    now() + interval '20 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Porto',
    'fuel',
    'watch',
    41.1684,
    -8.6412,
    '07:55',
    3,
    3,
    0,
    false,
    'A1 norte do Porto',
    'A1, Maia',
    'Porto',
    'Porto',
    'Portugal',
    now() - interval '3 days 8 hours',
    now() + interval '16 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Porto',
    'cargo_theft',
    'urgent',
    41.1498,
    -8.6123,
    '16:40',
    4,
    4,
    1,
    false,
    'Zona logística Leça da Palmeira',
    'Leça da Palmeira',
    'Porto',
    'Porto',
    'Portugal',
    now() - interval '12 days 4 hours',
    now() + interval '10 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Porto',
    'sos',
    'urgent',
    41.1421,
    -8.6587,
    '21:17',
    2,
    2,
    0,
    false,
    'Avaria + ambiente inseguro',
    'Matosinhos',
    'Porto',
    'Porto',
    'Portugal',
    now() - interval '6 days 9 hours',
    now() + interval '8 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Porto',
    'full_attack',
    'critical',
    41.1756,
    -8.5891,
    '02:44',
    7,
    7,
    0,
    false,
    'Assalto reportado em parque nocturno',
    'Parque industrial, Porto',
    'Porto',
    'Porto',
    'Portugal',
    now() - interval '4 days 1 hour',
    now() + interval '22 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Coimbra',
    'fuel',
    'watch',
    40.2187,
    -8.4289,
    '08:12',
    2,
    2,
    0,
    false,
    'A1 sul de Coimbra',
    'A1, Coimbra',
    'Coimbra',
    'Coimbra',
    'Portugal',
    now() - interval '7 days 6 hours',
    now() + interval '14 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Coimbra',
    'cargo_theft',
    'watch',
    40.1954,
    -8.4012,
    '13:28',
    1,
    1,
    0,
    false,
    'IC2 zona industrial',
    'Zona industrial, Coimbra',
    'Coimbra',
    'Coimbra',
    'Portugal',
    now() - interval '18 days 3 hours',
    now() + interval '12 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Coimbra',
    'sos',
    'urgent',
    40.2112,
    -8.4456,
    '19:51',
    3,
    3,
    0,
    false,
    'Pedido de apoio na A1',
    'A1, Coimbra',
    'Coimbra',
    'Coimbra',
    'Portugal',
    now() - interval '9 days 14 hours',
    now() + interval '6 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Coimbra',
    'full_attack',
    'critical',
    40.1876,
    -8.3798,
    '01:09',
    4,
    4,
    1,
    false,
    'Tentativa de roubo em área de serviço',
    'Área de serviço, Coimbra',
    'Coimbra',
    'Coimbra',
    'Portugal',
    now() - interval '15 days 7 hours',
    now() + interval '20 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Aveiro',
    'fuel',
    'info',
    40.6523,
    -8.6712,
    '10:33',
    1,
    1,
    0,
    false,
    'A25 próximo de Aveiro',
    'A25, Aveiro',
    'Aveiro',
    'Aveiro',
    'Portugal',
    now() - interval '11 days 2 hours',
    now() + interval '16 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Aveiro',
    'cargo_theft',
    'watch',
    40.6289,
    -8.6345,
    '15:47',
    2,
    2,
    0,
    false,
    'Plataforma logística Aveiro',
    'Ílhavo',
    'Aveiro',
    'Aveiro',
    'Portugal',
    now() - interval '22 days 5 hours',
    now() + interval '10 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Aveiro',
    'sos',
    'urgent',
    40.6412,
    -8.6987,
    '23:16',
    5,
    5,
    0,
    false,
    'SOS na A1/A25',
    'A1/A25, Aveiro',
    'Aveiro',
    'Aveiro',
    'Portugal',
    now() - interval '3 days 16 hours',
    now() + interval '5 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Aveiro',
    'full_attack',
    'critical',
    40.6156,
    -8.6521,
    '04:38',
    3,
    3,
    0,
    false,
    'Assalto em parque de estacionamento',
    'Estação de serviço, Aveiro',
    'Aveiro',
    'Aveiro',
    'Portugal',
    now() - interval '27 days 4 hours',
    now() + interval '18 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Braga',
    'fuel',
    'info',
    41.5512,
    -8.4389,
    '09:21',
    1,
    1,
    0,
    false,
    'A3 norte de Braga',
    'A3, Braga',
    'Braga',
    'Braga',
    'Portugal',
    now() - interval '20 days 8 hours',
    now() + interval '14 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Braga',
    'cargo_theft',
    'watch',
    41.5387,
    -8.4123,
    '17:02',
    2,
    2,
    1,
    false,
    'Zona industrial Braga',
    'Braga',
    'Braga',
    'Braga',
    'Portugal',
    now() - interval '25 days 11 hours',
    now() + interval '12 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Braga',
    'sos',
    'urgent',
    41.5623,
    -8.4567,
    '20:44',
    2,
    2,
    0,
    false,
    'Pedido SOS na A3',
    'A3, Braga',
    'Braga',
    'Braga',
    'Portugal',
    now() - interval '14 days 6 hours',
    now() + interval '7 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Braga',
    'full_attack',
    'critical',
    41.5289,
    -8.4012,
    '02:15',
    4,
    4,
    0,
    false,
    'Ataque reportado em parque industrial',
    'Parque industrial, Braga',
    'Braga',
    'Braga',
    'Portugal',
    now() - interval '29 days 3 hours',
    now() + interval '21 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Faro',
    'fuel',
    'watch',
    37.0312,
    -7.9456,
    '11:08',
    2,
    2,
    0,
    false,
    'A22 zona de Faro',
    'A22, Faro',
    'Faro',
    'Faro',
    'Portugal',
    now() - interval '16 days 9 hours',
    now() + interval '15 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Faro',
    'cargo_theft',
    'watch',
    37.0087,
    -7.9123,
    '14:36',
    1,
    1,
    0,
    false,
    'Plataforma logística Algarve',
    'Faro',
    'Faro',
    'Faro',
    'Portugal',
    now() - interval '24 days 7 hours',
    now() + interval '11 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Faro',
    'sos',
    'critical',
    37.0198,
    -7.9687,
    '22:52',
    3,
    3,
    0,
    false,
    'SOS na A22',
    'A22, Faro',
    'Faro',
    'Faro',
    'Portugal',
    now() - interval '10 days 13 hours',
    now() + interval '6 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Faro',
    'full_attack',
    'urgent',
    36.9956,
    -7.9345,
    '03:41',
    2,
    2,
    1,
    false,
    'Tentativa de assalto em área de descanso',
    'Área de serviço, Faro',
    'Faro',
    'Faro',
    'Portugal',
    now() - interval '28 days 2 hours',
    now() + interval '19 hours'
  ),

  -- ---------------------------------------------------------------------------
  -- ESPANHA (corredor Porto → Madrid)
  -- ---------------------------------------------------------------------------
  (
    '[SEED_ROUTE_RISK] Furto combustível — Madrid',
    'fuel',
    'urgent',
    40.4289,
    -3.7123,
    '07:18',
    5,
    5,
    0,
    false,
    'M-40 acesso Madrid',
    'M-40, Madrid',
    'Madrid',
    'Comunidad de Madrid',
    'España',
    now() - interval '2 days 6 hours',
    now() + interval '17 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Madrid',
    'cargo_theft',
    'watch',
    40.4012,
    -3.6789,
    '12:55',
    3,
    3,
    1,
    false,
    'Polígono industrial Getafe',
    'Getafe, Madrid',
    'Madrid',
    'Comunidad de Madrid',
    'España',
    now() - interval '13 days 4 hours',
    now() + interval '12 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Madrid',
    'sos',
    'critical',
    40.4156,
    -3.7456,
    '21:33',
    8,
    8,
    0,
    false,
    'SOS em corredor logístico',
    'Madrid',
    'Madrid',
    'Comunidad de Madrid',
    'España',
    now() - interval '1 day 4 hours',
    now() + interval '5 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Madrid',
    'full_attack',
    'critical',
    40.3923,
    -3.6912,
    '02:27',
    6,
    6,
    0,
    false,
    'Assalto em parque de camiões',
    'Parque camiões, Madrid',
    'Madrid',
    'Comunidad de Madrid',
    'España',
    now() - interval '6 days 8 hours',
    now() + interval '22 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Salamanca',
    'fuel',
    'watch',
    40.9812,
    -5.6789,
    '08:44',
    2,
    2,
    0,
    false,
    'A-62 Salamanca',
    'A-62, Salamanca',
    'Salamanca',
    'Castilla y León',
    'España',
    now() - interval '5 days 10 hours',
    now() + interval '16 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Salamanca',
    'cargo_theft',
    'watch',
    40.9587,
    -5.6412,
    '13:19',
    1,
    1,
    0,
    false,
    'Zona industrial Carbajosa',
    'Salamanca',
    'Salamanca',
    'Castilla y León',
    'España',
    now() - interval '17 days 2 hours',
    now() + interval '11 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Salamanca',
    'sos',
    'urgent',
    40.9723,
    -5.7012,
    '20:06',
    4,
    4,
    0,
    false,
    'SOS na A-62',
    'A-62, Salamanca',
    'Salamanca',
    'Castilla y León',
    'España',
    now() - interval '8 days 15 hours',
    now() + interval '7 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Salamanca',
    'full_attack',
    'critical',
    40.9456,
    -5.6234,
    '01:48',
    3,
    3,
    0,
    false,
    'Ataque em área de serviço',
    'Área de serviço, Salamanca',
    'Salamanca',
    'Castilla y León',
    'España',
    now() - interval '21 days 6 hours',
    now() + interval '20 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Valladolid',
    'fuel',
    'info',
    41.6612,
    -4.7389,
    '09:37',
    2,
    2,
    0,
    false,
    'A-62 Valladolid',
    'A-62, Valladolid',
    'Valladolid',
    'Castilla y León',
    'España',
    now() - interval '9 days 3 hours',
    now() + interval '15 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Valladolid',
    'cargo_theft',
    'urgent',
    41.6387,
    -4.7012,
    '15:22',
    3,
    3,
    1,
    false,
    'Polígono Arroyo',
    'Valladolid',
    'Valladolid',
    'Castilla y León',
    'España',
    now() - interval '19 days 8 hours',
    now() + interval '10 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Valladolid',
    'sos',
    'urgent',
    41.6523,
    -4.7567,
    '22:14',
    2,
    2,
    0,
    false,
    'SOS corredor A-62',
    'A-62, Valladolid',
    'Valladolid',
    'Castilla y León',
    'España',
    now() - interval '4 days 12 hours',
    now() + interval '6 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Valladolid',
    'full_attack',
    'critical',
    41.6289,
    -4.6789,
    '03:05',
    5,
    5,
    0,
    false,
    'Assalto reportado em parque logístico',
    'Parque logístico, Valladolid',
    'Valladolid',
    'Castilla y León',
    'España',
    now() - interval '26 days 5 hours',
    now() + interval '21 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Burgos',
    'fuel',
    'watch',
    42.3512,
    -3.7123,
    '08:09',
    3,
    3,
    0,
    false,
    'A-1 Burgos',
    'A-1, Burgos',
    'Burgos',
    'Castilla y León',
    'España',
    now() - interval '7 days 7 hours',
    now() + interval '16 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Burgos',
    'cargo_theft',
    'watch',
    42.3287,
    -3.6789,
    '14:48',
    2,
    2,
    0,
    false,
    'Zona industrial Burgos',
    'Burgos',
    'Burgos',
    'Castilla y León',
    'España',
    now() - interval '23 days 4 hours',
    now() + interval '12 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Burgos',
    'sos',
    'critical',
    42.3423,
    -3.7345,
    '21:57',
    4,
    4,
    0,
    false,
    'SOS na A-1',
    'A-1, Burgos',
    'Burgos',
    'Castilla y León',
    'España',
    now() - interval '3 days 9 hours',
    now() + interval '5 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Burgos',
    'full_attack',
    'critical',
    42.3156,
    -3.6512,
    '02:33',
    6,
    6,
    1,
    false,
    'Ataque em área de descanso A-1',
    'Área de descanso, Burgos',
    'Burgos',
    'Castilla y León',
    'España',
    now() - interval '11 days 1 hour',
    now() + interval '22 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Irún',
    'fuel',
    'info',
    43.3456,
    -1.8012,
    '10:26',
    1,
    1,
    0,
    false,
    'A-8 fronteira PT/ES',
    'A-8, Irún',
    'Irún',
    'País Vasco',
    'España',
    now() - interval '15 days 6 hours',
    now() + interval '14 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Irún',
    'cargo_theft',
    'watch',
    43.3289,
    -1.7723,
    '16:11',
    2,
    2,
    0,
    false,
    'Parque logístico fronteira',
    'Irún',
    'Irún',
    'País Vasco',
    'España',
    now() - interval '27 days 9 hours',
    now() + interval '11 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Irún',
    'sos',
    'urgent',
    43.3512,
    -1.8234,
    '23:42',
    3,
    3,
    0,
    false,
    'SOS na fronteira',
    'Fronteira, Irún',
    'Irún',
    'País Vasco',
    'España',
    now() - interval '12 days 11 hours',
    now() + interval '6 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Irún',
    'full_attack',
    'critical',
    43.3123,
    -1.7567,
    '04:19',
    4,
    4,
    0,
    false,
    'Assalto em parque de estacionamento',
    'Parque, Irún',
    'Irún',
    'País Vasco',
    'España',
    now() - interval '29 days 8 hours',
    now() + interval '20 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Barcelona',
    'fuel',
    'watch',
    41.3987,
    2.1789,
    '07:42',
    3,
    3,
    0,
    false,
    'Ronda Litoral Barcelona',
    'Barcelona',
    'Barcelona',
    'Cataluña',
    'España',
    now() - interval '14 days 3 hours',
    now() + interval '17 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Barcelona',
    'cargo_theft',
    'urgent',
    41.3723,
    2.1456,
    '13:07',
    4,
    4,
    1,
    false,
    'Zona franca/logística',
    'Zona logística, Barcelona',
    'Barcelona',
    'Cataluña',
    'España',
    now() - interval '20 days 5 hours',
    now() + interval '12 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Barcelona',
    'sos',
    'critical',
    41.3856,
    2.1912,
    '22:28',
    5,
    5,
    0,
    false,
    'SOS porto/logística',
    'Barcelona',
    'Barcelona',
    'Cataluña',
    'España',
    now() - interval '6 days 16 hours',
    now() + interval '5 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Barcelona',
    'full_attack',
    'critical',
    41.3612,
    2.1234,
    '01:56',
    3,
    3,
    0,
    false,
    'Ataque em parque industrial',
    'Parque industrial, Barcelona',
    'Barcelona',
    'Cataluña',
    'España',
    now() - interval '25 days 2 hours',
    now() + interval '21 hours'
  ),

  -- ---------------------------------------------------------------------------
  -- FRANÇA
  -- ---------------------------------------------------------------------------
  (
    '[SEED_ROUTE_RISK] Furto combustível — Bordeaux',
    'fuel',
    'watch',
    44.8489,
    -0.5912,
    '08:31',
    2,
    2,
    0,
    false,
    'A630 Bordeaux',
    'A630, Bordeaux',
    'Bordeaux',
    'Nouvelle-Aquitaine',
    'France',
    now() - interval '18 days 4 hours',
    now() + interval '16 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Bordeaux',
    'cargo_theft',
    'watch',
    44.8212,
    -0.5567,
    '14:59',
    1,
    1,
    0,
    false,
    'Zone logistique Bordeaux',
    'Bordeaux',
    'Bordeaux',
    'Nouvelle-Aquitaine',
    'France',
    now() - interval '24 days 6 hours',
    now() + interval '11 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Bordeaux',
    'sos',
    'urgent',
    44.8356,
    -0.6123,
    '21:14',
    3,
    3,
    0,
    false,
    'SOS rocade Bordeaux',
    'Rocade, Bordeaux',
    'Bordeaux',
    'Nouvelle-Aquitaine',
    'France',
    now() - interval '10 days 8 hours',
    now() + interval '7 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Bordeaux',
    'full_attack',
    'critical',
    44.8123,
    -0.5345,
    '03:27',
    4,
    4,
    0,
    false,
    'Agression aire de repos',
    'Aire de repos, Bordeaux',
    'Bordeaux',
    'Nouvelle-Aquitaine',
    'France',
    now() - interval '28 days 7 hours',
    now() + interval '20 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Toulouse',
    'fuel',
    'info',
    44.6123,
    1.4567,
    '09:18',
    2,
    2,
    0,
    false,
    'Périphérique Toulouse',
    'Toulouse',
    'Toulouse',
    'Occitanie',
    'France',
    now() - interval '16 days 10 hours',
    now() + interval '15 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Toulouse',
    'cargo_theft',
    'watch',
    44.5889,
    1.4234,
    '15:33',
    2,
    2,
    1,
    false,
    'Zone logistique Toulouse',
    'Toulouse',
    'Toulouse',
    'Occitanie',
    'France',
    now() - interval '22 days 3 hours',
    now() + interval '12 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Toulouse',
    'sos',
    'urgent',
    44.6012,
    1.4789,
    '20:47',
    3,
    3,
    0,
    false,
    'SOS rocade sud',
    'Rocade, Toulouse',
    'Toulouse',
    'Occitanie',
    'France',
    now() - interval '7 days 13 hours',
    now() + interval '6 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Toulouse',
    'full_attack',
    'critical',
    44.5756,
    1.4012,
    '02:08',
    5,
    5,
    0,
    false,
    'Agression parking poids lourds',
    'Parking PL, Toulouse',
    'Toulouse',
    'Occitanie',
    'France',
    now() - interval '26 days 9 hours',
    now() + interval '21 hours'
  ),

  (
    '[SEED_ROUTE_RISK] Furto combustível — Lyon',
    'fuel',
    'watch',
    44.7723,
    4.8512,
    '08:55',
    3,
    3,
    0,
    false,
    'A6 nord Lyon',
    'A6, Lyon',
    'Lyon',
    'Auvergne-Rhône-Alpes',
    'France',
    now() - interval '13 days 5 hours',
    now() + interval '16 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Roubo de carga — Lyon',
    'cargo_theft',
    'urgent',
    44.7489,
    4.8123,
    '14:21',
    4,
    4,
    0,
    false,
    'Zone logistique Lyon',
    'Lyon',
    'Lyon',
    'Auvergne-Rhône-Alpes',
    'France',
    now() - interval '19 days 7 hours',
    now() + interval '11 hours'
  ),
  (
    '[SEED_ROUTE_RISK] SOS — Lyon',
    'sos',
    'critical',
    44.7612,
    4.8789,
    '23:03',
    6,
    6,
    0,
    false,
    'SOS A6/A7',
    'A6/A7, Lyon',
    'Lyon',
    'Auvergne-Rhône-Alpes',
    'France',
    now() - interval '5 days 14 hours',
    now() + interval '5 hours'
  ),
  (
    '[SEED_ROUTE_RISK] Ataque — Lyon',
    'full_attack',
    'critical',
    44.7345,
    4.7923,
    '01:34',
    4,
    4,
    1,
    false,
    'Agression aire de repos A6',
    'Aire de repos, Lyon',
    'Lyon',
    'Auvergne-Rhône-Alpes',
    'France',
    now() - interval '30 days 1 hour',
    now() + interval '22 hours'
  );

-- Resumo para validação rápida
select
  country,
  city,
  type,
  severity,
  count(*) as alertas,
  min(created_at) as mais_antigo,
  max(created_at) as mais_recente
from public.alerts
where title like '[SEED_ROUTE_RISK]%'
group by country, city, type, severity
order by country, city, type;

select
  type,
  count(*) as total
from public.alerts
where title like '[SEED_ROUTE_RISK]%'
group by type
order by type;

commit;
